### ISSUE TITLE
Add support for Path/Prefix in S3 KB Source

### ISSUE THREAD

**Issue by schammah** [aws-ia/terraform-aws-bedrock#45]
When using `kb_s3_data_source` add support to specify the prefix/path for the data source, 
for if you don't want to use the root of the bucket as your source

2 options for implementation:
1. turn variable into a map something similar to
```
  kb_s3_data_source = {
    s3_bucket = "bedrock-data"
    s3_prefix = "myprefix"
  }
```
3. add another variable such as `kb_s3_data_source_prefix`

**Comment by alexa-perlov** [comment]
` kb_s3_data_source` represents the ARN of the S3 data source for the knowledge base. The Terraform `aws_bedrockagent_data_source` resource doesn't take in any S3 prefix or path but rather uses this ARN. Please let me know if any issues come up with using the existing bucket ARN as the ` kb_s3_data_source`.

**Comment by schammah** [comment]
@alexa-perlov , thank you for the assistance, but when using the arn you cannot specify a full path in s3 to use as data_source due validation of the arn, meaning its an issue, or a request to support something more than just the s3 bucket itself

here's the error when trying to specify the arn with a full path:

```

│ Error: updating Bedrock Agent Data Source (I5PWKBYUY4)
│
│   with module.bedrock.aws_bedrockagent_data_source.knowledge_base_ds[0],
│   on .terraform/modules/bedrock/data-source.tf line 36, in resource "aws_bedrockagent_data_source" "knowledge_base_ds":
│   36: resource "aws_bedrockagent_data_source" "knowledge_base_ds" {
│
│ operation error Bedrock Agent: UpdateDataSource, https response error StatusCode: 400, RequestID: 28ec7fb6-690a-4ca0-abf2-7e6be1558361, ValidationException: 1 validation error
│ detected: Value 'arn:aws:s3:::ask-service-c-usea1-660079207827/kb/' at 'dataSourceConfiguration.s3Configuration.bucketArn' failed to satisfy constraint: Member must satisfy
│ regular expression pattern: arn:aws(|-cn|-us-gov):s3:::[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]
╵
```

**Comment by alexa-perlov** [comment]
Ah I see, thank you for the additional information. The validation is coming from the AWS provider itself and not this bedrock module (which is calling the provider). This means it's actually an issue on the AWS provider side which can be reported here: https://github.com/hashicorp/terraform-provider-aws/issues

**Comment by schammah** [comment]
@alexa-perlov i've taken a look at the provider is fine, please refer to [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/bedrockagent_data_source#s3_data_source_configuration-block).
the implementation should be different , their `[s3_data_source_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/bedrockagent_data_source#s3_data_source_configuration-block)` can be defined with the bucket arn + a list of prefixes: as shown [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/bedrockagent_data_source#inclusion_prefixes-1)
do you think we could add support for that in this module implementation?

**Comment by schammah** [comment]
@alexa-perlov hey, didn't get any comments from you, is it possible for me to contribue this to the module?

**Comment by alexa-perlov** [comment]
@schammah sorry for the delay, it's been updated and the latest version has been released.
