### ISSUE TITLE
Guardrail example use invalid parameter

### ISSUE THREAD

**Issue by wellsiau-aws** [aws-ia/terraform-aws-bedrock#48]
Example for bedrock guardrail as described [here](https://registry.terraform.io/modules/aws-ia/bedrock/aws/latest#bedrock-guardrails) is using invalid parameter:

```
module "bedrock" {
  source  = "aws-ia/bedrock/aws"
  version = "0.0.5"
  ...
  blocked_input = "Blocked input" # invalid
  blocked_output = "Blocked output" #invalid
  ...
}
```

**Comment by alexa-perlov** [comment]
readme has been updated with valid bedrock guardrail parameters – thank you!
